[package]
name = "dist-render-simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dist-render = { path = "../dist-render" }
dist-render-egui = { path = "../dist-render-egui", optional = true }

anyhow = "1.0"
egui = { version = "0.15", default-features = false, features = ["default_fonts", "single_threaded"], optional = true }
glam = { version = "0.22", features = ["serde"] }
log = "0.4"
puffin = { version = "0.11.0" }
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }
winit = "0.25"

puffin_http = { version = "0.8.0", optional = true }

[features]
egui = [
    "dep:egui",
    "dist-render-egui",
]
puffin-server = [
    "puffin_http",
]
winit_serde = [
    "winit/serde",
]
